name: Test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      pull-requests: write
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v3

    - name: Install
      run: npm i

    - name: Lint
      run: npm run lint

    - name: Tests
      run: npm run test:ci

    - name: Comment Test Coverage
      if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened')
      uses: MishaKav/jest-coverage-comment@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        coverage-summary-path: coverage/coverage-summary.json
        title: Jest Test Coverage